---
title: "Walmart Interview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import packages

library(data.table) ## for importing data
library(tidyverse) ## for data wrangling
library(stringr) ## for string manipulation
library(plotly)
library(dplyr)
library(Hmisc)

##set working directory
setwd('C:/OneDrive/OneDrive - Tredence/Attachments/Omni Channel-Walmart Interview/Interview/ml-latest-small')

links<-read.csv('links.csv',stringsAsFactors = F)
movies<-read.csv('movies.csv',stringsAsFactors = F)
ratings<-read.csv('ratings.csv',stringsAsFactors = F)
tags<-read.csv('tags.csv',stringsAsFactors = F)

##Data Manipulations before solving the questions
##Exrtact year and title out of title column and split genre in movies df
movies<-movies %>%  
  mutate(year=as.numeric(substr(title,unlist(regexpr("\\([0-9\\-]*\\)$",title))+1,unlist(regexpr("\\([0-9\\-]*\\)$",title))+4)),
         title_new=substr(title,1,ifelse(unlist(regexpr("\\([0-9\\-]*\\)$",title))-1==-2,nchar(title),unlist(regexpr("\\([0-9\\-]*\\)$",title))-1)),
         genre=strsplit(genres,"\\|")) %>%
  unnest(genre)

movies<-movies[complete.cases(movies),]

##convert unix timestamp to standard dates
tags<-tags%>% mutate(tags_Date=as.Date(as.POSIXct(timestamp,origin="1970-01-01",tz="GMT")),
                     tags_year=year(tags_Date))

ratings<-ratings%>% mutate(rat_Date=as.Date(as.POSIXct(timestamp,origin="1970-01-01",tz="GMT")),
                           rat_year=year(rat_Date))


## The Hypothesis:
##" count of movie produced per year depends on rating and total reviews of the movies of past years by genre- 
##We will be doing this for most popular genre and from 2000-2015. Popular would be decided by the maximum number 
##of movies across  years"

## Steps to be followed:
# 1. Find the most popular genre
# 2. Find total number of movies made in that genre in 2000-2015
# 3. Find avg rating
# 4. Cross reference step 2 and 3 to find out the nature of the relation, if any

##Assumptions:
##Data is holistic to be used for the analysis

#1.Find the most popular genre

genre<-movies%>%
      distinct(movieId,genre)%>%
      group_by(genre)%>% summarise(count=n())%>% filter(row_number(desc(count))==1)
## genre is drama

# 2. Find total number of movies made in that genre in 2000-2015

movie_per_year<-movies%>%
                distinct( movieId,year,genre)%>%
                filter(year >= 2000 & year <= 2015)%>%
                filter(genre =='Drama')%>%
                group_by(year)%>%
                summarise(movie_count=n())


# 3. Find avg rating

rat_per_year<- movies%>%
               distinct( movieId,year,genre)%>%
               filter( genre == "Drama")%>%
               filter(year >= 2000 & year <= 2015)%>%
               left_join(ratings, by = "movieId")%>%
               group_by(year)%>%
               summarise(avg_rating=mean(rating,na.rm = T),
                         rev_count=n_distinct(userId))

## Joining the 2

count_rat_per_year<-left_join(movie_per_year,rat_per_year)

plot1<-count_rat_per_year%>%
      ggplot()+ geom_line(aes(x=year,y=movie_count,color="red"))+
      geom_line(aes(x=year,y=rev_count,color="blue" ))+
      geom_line(aes(x=year,y=avg_rating,color="green" ))

ggplotly(plot1)
        
rcorr(as.matrix(count_rat_per_year))
# year   movie_count avg_rating rev_count
# year               0.0001      0.4425     0.0000   
# movie_count 0.0001             0.7595     0.0022   
# avg_rating  0.4425 0.7595                 0.0833   
# rev_count   0.0000 0.0022      0.0833  
### From data and chart its clear that there is more or less no impact of 
## avg ratings and number of reviews on the count of movies being made
```

## Including Plots

You can also embed plots, for example:

plot1<-count_rat_per_year%>%
      ggplot()+ geom_line(aes(x=year,y=movie_count,color="red"))+
      geom_line(aes(x=year,y=rev_count,color="blue" ))+
      geom_line(aes(x=year,y=avg_rating,color="green" ))

ggplotly(plot1)

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
